version: '3.1'

services:
  csci-602-database:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: competition
    ports:
      - "5433:5432"
    container_name: csci-602-database